// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'item_catalog_info.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'item_catalog_info.g.dart';

@freezed
class ItemCatalogInfo with _$ItemCatalogInfo {
  const factory ItemCatalogInfo({
    required String article,
    required String uom,
    required String category,
    required String categoryDesc,
    required String subSegment,
    required String subSegmentDesc,
    required String brand,
    required String brandDesc,
    required String substrate,
    required String substrateDesc,
    required String value1,
    required String value2,
    required String value3,
    required String value4,
    required String value5,
    required String value6,
    required String value7,
    required String value8,
    required String value9,
    required String value10,
    required String text1,
    required String text2,
    required String text3,
    required String text4,
    required String text5,
    required String text6,
    required String text7,
    required String text8,
    required String text9,
    required String text10,
  }) = _ItemCatalogInfo;

  factory ItemCatalogInfo.fromJson(Map<String, Object?> json) =>
      _$ItemCatalogInfoFromJson(json);
}
