// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'order_detail_line.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'order_detail_line.g.dart';

@freezed
class OrderDetailLine with _$OrderDetailLine {
  factory OrderDetailLine({
    required String company,
    required int orderNumber,
    required String orderType,
    required double lineNumber,
    required DateTime? dateShipped,
    required DateTime? dateInvoiced,
    required String item,
    required String itemDescription,
    required String userComment,
    required String nextStatus,
    required String nextStatusDescription,
    required String lastStatus,
    required String lastStatusDescription,
    required int quantityOrdered,
    required int quantityCancelled,
    required int quantityBackordered,
    required int invoiceNumber,
    required String invoiceType,
    required String invoiceCompany,
    required int workOrderNumber,
    required String workOrderType,
    required String woStatus,
    required String catalogName,
  }) = _OrderDetailLine;

  OrderDetailLine._();

  String get status {
    // Labdip
    if (orderType == 'LD' && workOrderType == 'W6') {
      switch (woStatus) {
        case '10':
        case '15':
          return 'Order Received By Branch';
        case '20':
          return 'Order Received By Plant';
        case '41':
          return 'Dispatched';
        default:
          return 'In Progress';
      }
    }
    return 'Unknown';
  }

  factory OrderDetailLine.fromJson(Map<String, Object?> json) =>
      _$OrderDetailLineFromJson(json);
}
