// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_address.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_address.g.dart';

@freezed
class UserAddress with _$UserAddress {
  const factory UserAddress({
    required String alphaName,
    required String addressLine1,
    required String addressLine2,
    required String addressLine3,
    required String addressLine4,
    required String city,
    required String postalCode,
    required String state,
    required String stateCode,
    required String country,
    required String countryCode,
    required int deliveryAddressNumber,
    String? branchPlant,
  }) = _UserAddress;

  factory UserAddress.fromJson(Map<String, Object?> json) =>
      _$UserAddressFromJson(json);
}
