name: vardhman_b2b
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  video_player_media_kit: ^1.0.5
  media_kit_libs_windows_video: any
  data_table_2: ^2.5.18
  date_field: ^6.0.3+1
  device_info_plus: ^11.2.2
  dio: ^5.7.0
  drift: ^2.24.0
  drift_db_viewer: ^2.1.0
  drift_flutter: ^0.2.4
  dropdown_search: ^6.0.2
  excel: ^4.0.6
  file_picker: ^8.1.7
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  # js: ^0.7.1
  path_provider: ^2.1.5
  pdfrx: ^1.0.101
  permission_handler: ^11.3.1
  pure_ftp: ^0.7.5
  searchfield: ^1.2.2
  shared_preferences: ^2.3.5
  # speech_to_text: ^7.0.0
  toastification: ^2.3.0
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  video_player: ^2.9.3
  # web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  drift_dev: ^2.24.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
