const labdipOrders = [
  {
    "S No.": "1",
    "Order Date": "25-06-2024",
    "Estimated Delivery Date": "30-06-2024",
    "Order Id": "353",
    "Order Line": "Line #1",
    "Article": "8822",
    "tex": "24",
    "Ticket": "NOT KNOWN",
    "Quantity": "1",
    "Brand": "ANESOFT",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "2",
    "Order Date": "25-06-2024",
    "Estimated Delivery Date": "30-06-2024",
    "Order Id": "352",
    "Order Line": "Line #1",
    "Article": "8888",
    "tex": "18",
    "Ticket": "NOT KNOWN",
    "Quantity": "1",
    "Brand": "WILD CAT",
    "End Use": "Apparel",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "3",
    "Order Date": "25-06-2024",
    "Estimated Delivery Date": "30-06-2024",
    "Order Id": "351",
    "Order Line": "Line #1",
    "Article": "8888",
    "tex": "18",
    "Ticket": "NOT KNOWN",
    "Quantity": "1",
    "Brand": "WILD CAT",
    "End Use": "Apparel",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "4",
    "Order Date": "07-08-2023",
    "Estimated Delivery Date": "12-08-2023",
    "Order Id": "306",
    "Order Line": "Line #1",
    "Article": "A9565",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "Cowboy",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "5",
    "Order Date": "07-08-2023",
    "Estimated Delivery Date": "12-08-2023",
    "Order Id": "306",
    "Order Line": "Line #2",
    "Article": "RA4560",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "ANE ECO100",
    "End Use": "Active/sportswear",
    "Shade": "SWT2",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "Other",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "6",
    "Order Date": "07-08-2023",
    "Estimated Delivery Date": "12-08-2023",
    "Order Id": "306",
    "Order Line": "Line #3",
    "Article": "NOT KNOWN",
    "tex": "70",
    "Ticket": "40",
    "Quantity": "1",
    "Brand": "ANE ECO100",
    "End Use": "Active/sportswear",
    "Shade": "SWT2",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "Other",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "7",
    "Order Date": "07-08-2023",
    "Estimated Delivery Date": "12-08-2023",
    "Order Id": "306",
    "Order Line": "Line #4",
    "Article": "NOT KNOWN",
    "tex": "35",
    "Ticket": "50",
    "Quantity": "1",
    "Brand": "3+SUP-SEAM",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "Other",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "8",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "296",
    "Order Line": "Line #1",
    "Article": "A9563",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "LINKER",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "9",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "295",
    "Order Line": "Line #1",
    "Article": "A9560",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "LINKER",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "10",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "294",
    "Order Line": "Line #1",
    "Article": "NOT KNOWN",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "Cowboy",
    "End Use": "Active/sportswear",
    "Shade": "SWT2",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "11",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "294",
    "Order Line": "Line #2",
    "Article": "1322",
    "tex": "24",
    "Ticket": "NOT KNOWN",
    "Quantity": "1",
    "Brand": "WILD CAT",
    "End Use": "Apparel",
    "Shade": "SWT2",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "12",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "292",
    "Order Line": "Line #1",
    "Article": "A9565",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "Cowboy",
    "End Use": "Active/sportswear",
    "Shade": "P170",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "13",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "292",
    "Order Line": "Line #2",
    "Article": "NOT KNOWN",
    "tex": "70",
    "Ticket": "40",
    "Quantity": "1",
    "Brand": "ANE ECO100",
    "End Use": "Active/sportswear",
    "Shade": "SWT2",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "14",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "291",
    "Order Line": "Line #1",
    "Article": "A9565",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "Cowboy",
    "End Use": "Active/sportswear",
    "Shade": "P170",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "15",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "291",
    "Order Line": "Line #2",
    "Article": "NOT KNOWN",
    "tex": "70",
    "Ticket": "40",
    "Quantity": "1",
    "Brand": "ANE ECO100",
    "End Use": "Active/sportswear",
    "Shade": "SWT2",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "16",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "290",
    "Order Line": "Line #1",
    "Article": "A9565",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "Cowboy",
    "End Use": "Active/sportswear",
    "Shade": "P170",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  },
  {
    "S No.": "17",
    "Order Date": "04-08-2023",
    "Estimated Delivery Date": "09-08-2023",
    "Order Id": "289",
    "Order Line": "Line #1",
    "Article": "NOT KNOWN",
    "tex": "45",
    "Ticket": "60",
    "Quantity": "1",
    "Brand": "LINKER",
    "End Use": "Apparel",
    "Shade": "P238",
    "Permanent Shade no.": "",
    "QTX/XML File": "",
    "Buyer Name": "GAP",
    "Order Status": "Pending",
    "Dispatch Date": "",
    "Action": "Order Feedback"
  }
];

const dtmOrders = [
  {
    "S No.": "1",
    "Order Date": "25-06-2024",
    "Order Id": "118",
    "Order Line": "Line #1",
    "Article": "AA930",
    "tex": "30",
    "Ticket": "NOT KNOWN",
    "Brand": "PERMA CORE",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade No.": "",
    "Quantity": "100",
    "Buyer Name": "GAP",
    "Order Status": "Pending"
  },
  {
    "S No.": "2",
    "Order Date": "04-08-2023",
    "Order Id": "106",
    "Order Line": "Line #1",
    "Article": "AA930",
    "tex": "30",
    "Ticket": "NOT KNOWN",
    "Brand": "PERMA CORE",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade No.": "",
    "Quantity": "1",
    "Buyer Name": "Other",
    "Order Status": "Pending"
  },
  {
    "S No.": "3",
    "Order Date": "04-08-2023",
    "Order Id": "105",
    "Order Line": "Line #1",
    "Article": "AA930",
    "tex": "30",
    "Ticket": "NOT KNOWN",
    "Brand": "PERMA CORE",
    "End Use": "Active/sportswear",
    "Shade": "SWT1",
    "Permanent Shade No.": "",
    "Quantity": "1",
    "Buyer Name": "GAP",
    "Order Status": "Pending"
  }
];

const bulkOrders = [
  {
    "S No.": "1",
    "Creation Date": "25-06-2024",
    "Estimated Delivery Date": "10-07-2024",
    "Customer Name": "LIBERTY FOOTWEAR COMPANY",
    "PO Number": "a112",
    "Ship To Party": "LIBERTY SHOES CO.",
    "Order No.": "135",
    "Order Line No.": "Line #1",
    "Total Quantity": "12",
    "Invoice Amount": "Rs.0",
    "Payable Amount": "Rs.0",
    "Order Status": "Pending"
  }
];
